# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-06 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=37)),
                ('content', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=37)),
                ('parent_uuid', models.CharField(max_length=37)),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
