# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-21 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contents',
            old_name='index',
            new_name='uuid',
        ),
    ]
