# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-21 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20190521_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='modifyDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
